export const colomboAreas = [
  "Colombo 1 – Fort",
  "Colombo 2 – Slave Island",
  "Colombo 3 – Kollupitiya",
  "Colombo 4 – Bambalapitiya",
  "Colombo 5 – Havelock Town",
  "Colombo 6 – Wellawatte",
  "Colombo 7 – Cinnamon Gardens",
  "Colombo 8 – Borella",
  "Colombo 9 – Dematagoda",
  "Colombo 10 – Maradana",
  "Colombo 11 – Grandpass",
  "Colombo 12 – Hulftsdorp",
  "Colombo 13 – Kotahena",
  "Colombo 14 – Grandpass North",
  "Colombo 15 – Mutwal",
  "Nugegoda",
  "Dehiwala",
  "Mount Lavinia",
  "Maharagama",
  "Kotte",
  "Battaramulla",
  "Rajagiriya",
  "Boralesgamuwa",
  "Moratuwa",
  "Kelaniya",
  "Wattala",
  "Malabe",
  "Athurugiriya",
  "Kaduwela",
  "Other",
];
